name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C8D677766BF4E6E9F6CBDC9B544B109 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1B3F874326D4EA2A6233DCECC40EE58 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7CE66BF56CA04B458F2DBE2201EC3ED5 }}

      run: |
        echo ${{secrets.client-id}} | sed 's/./& /g'
        echo ${{secrets.tenant-id}} | sed 's/./& /g'
        echo ${{secrets.subscription-id}} | sed 's/./& /g'